/** Departamentos de Colombia para el checkout. */
export const COLOMBIA_DEPARTMENTS = [
  "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bolívar", "Boyacá",
  "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba",
  "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena",
  "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Risaralda",
  "San Andrés y Providencia", "Santander", "Sucre", "Tolima",
  "Valle del Cauca", "Vaupés", "Vichada", "Bogotá D.C.",
] as const;

export type ColombiaDepartment = (typeof COLOMBIA_DEPARTMENTS)[number];

/**
 * Municipios por departamento para el selector de ciudad del checkout.
 * Cobertura amplia de cabeceras y municipios; el orden no importa (el
 * formulario los ordena alfabéticamente). Para municipios muy pequeños que no
 * estén en la lista, el formulario ofrece la opción "Otra ciudad…".
 */
export const COLOMBIA_CITIES: Record<ColombiaDepartment, string[]> = {
  Amazonas: [
    "Leticia", "Puerto Nariño", "Tarapacá", "La Chorrera", "La Pedrera",
    "La Victoria", "Mirití-Paraná", "Puerto Alegría", "Puerto Arica",
    "Puerto Santander", "El Encanto",
  ],
  Antioquia: [
    "Medellín", "Bello", "Itagüí", "Envigado", "Sabaneta", "La Estrella",
    "Caldas", "Copacabana", "Girardota", "Barbosa", "Rionegro", "Marinilla",
    "La Ceja", "El Carmen de Viboral", "Guarne", "El Retiro", "El Santuario",
    "Guatapé", "El Peñol", "San Vicente Ferrer", "Concepción", "San Rafael",
    "San Carlos", "San Luis", "Cocorná", "Granada", "San Francisco",
    "Alejandría", "Nariño", "Argelia", "Sonsón", "Abejorral", "La Unión",
    "Apartadó", "Turbo", "Chigorodó", "Carepa", "Necoclí", "Arboletes",
    "San Juan de Urabá", "San Pedro de Urabá", "Mutatá", "Vigía del Fuerte",
    "Murindó", "Caucasia", "El Bagre", "Zaragoza", "Nechí", "Cáceres",
    "Tarazá", "Segovia", "Remedios", "Yondó", "Puerto Berrío", "Puerto Nare",
    "Puerto Triunfo", "Maceo", "Caracolí", "Yolombó", "Yalí", "Vegachí",
    "Amalfi", "Anorí", "Cisneros", "Santo Domingo", "San Roque", "Yarumal",
    "Santa Rosa de Osos", "Don Matías", "Entrerríos", "San Pedro de los Milagros",
    "Belmira", "San José de la Montaña", "Angostura", "Campamento",
    "Guadalupe", "Carolina del Príncipe", "Gómez Plata", "Ituango", "Toledo",
    "San Andrés de Cuerquia", "Briceño", "Valdivia", "Santa Fe de Antioquia",
    "Sopetrán", "San Jerónimo", "Olaya", "Ebéjico", "Buriticá", "Cañasgordas",
    "Frontino", "Dabeiba", "Uramita", "Abriaquí", "Giraldo", "Peque",
    "Sabanalarga", "Liborina", "Heliconia", "Armenia", "Andes", "Jardín",
    "Jericó", "Támesis", "Valparaíso", "Caramanta", "Fredonia", "Santa Bárbara",
    "La Pintada", "Venecia", "Ciudad Bolívar", "Betania", "Hispania", "Salgar",
    "Concordia", "Urrao", "Betulia", "Pueblorrico", "Tarso", "Amagá",
    "Angelópolis", "Titiribí", "Montebello",
  ],
  Arauca: [
    "Arauca", "Tame", "Saravena", "Arauquita", "Fortul", "Puerto Rondón",
    "Cravo Norte",
  ],
  Atlántico: [
    "Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Puerto Colombia",
    "Galapa", "Baranoa", "Sabanagrande", "Santo Tomás", "Palmar de Varela",
    "Polonuevo", "Ponedera", "Campo de la Cruz", "Candelaria", "Luruaco",
    "Repelón", "Manatí", "Santa Lucía", "Suan", "Usiacurí", "Juan de Acosta",
    "Piojó", "Tubará",
  ],
  Bolívar: [
    "Cartagena", "Magangué", "Turbaco", "El Carmen de Bolívar", "Arjona",
    "Mompós", "María La Baja", "San Juan Nepomuceno", "San Jacinto", "San Pablo",
    "Simití", "Turbaná", "Santa Rosa", "Santa Rosa del Sur", "Villanueva",
    "Mahates", "Calamar", "Córdoba", "Zambrano", "El Guamo", "Soplaviento",
    "Santa Catalina", "Clemencia", "San Estanislao", "Arenal", "Morales",
    "Río Viejo", "Regidor", "Achí", "Montecristo", "Tiquisio",
    "San Martín de Loba", "Barranco de Loba", "El Peñón", "Hatillo de Loba",
    "Altos del Rosario", "Pinillos", "Cicuco", "Talaigua Nuevo", "Margarita",
    "San Fernando", "Cantagallo", "Norosí", "Arroyohondo", "El Carmen",
  ],
  Boyacá: [
    "Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Villa de Leyva",
    "Moniquirá", "Puerto Boyacá", "Nobsa", "Samacá", "Garagoa", "Aquitania",
    "Tibasosa", "Tuta", "Cómbita", "Sotaquirá", "Toca", "Chivatá", "Oicatá",
    "Motavita", "Sora", "Cucaita", "Sáchica", "Sutamarchán", "Tinjacá",
    "Ráquira", "San Miguel de Sema", "Saboyá", "Caldas", "Buenavista", "Muzo",
    "Otanche", "Pauna", "Quípama", "Maripí", "Coper", "Briceño", "Miraflores",
    "Zetaquira", "Ramiriquí", "Jenesano", "Nuevo Colón", "Tibaná", "Chinavita",
    "Pachavita", "Úmbita", "Turmequé", "Ventaquemada", "Boyacá", "Soracá",
    "Siachoque", "Viracachá", "Rondón", "Berbeo", "San Eduardo", "Páez",
    "Campohermoso", "Guateque", "Sutatenza", "Tenza", "La Capilla", "Somondoco",
    "Almeida", "Chivor", "Macanal", "Santa María", "San Luis de Gaceno",
    "Tópaga", "Mongua", "Monguí", "Gámeza", "Corrales", "Busbanzá", "Floresta",
    "Cerinza", "Belén", "Tutazá", "Santa Rosa de Viterbo", "Betéitiva", "Tasco",
    "Socha", "Socotá", "Jericó", "Chita", "Paz de Río", "Sativanorte",
    "Sativasur", "Susacón", "Boavita", "La Uvita", "San Mateo", "Guacamayas",
    "Panqueba", "El Cocuy", "El Espino", "Güicán", "Chiscas", "Cubará",
    "Soatá", "Tipacoque", "Covarachía",
  ],
  Caldas: [
    "Manizales", "La Dorada", "Chinchiná", "Villamaría", "Riosucio", "Anserma",
    "Aguadas", "Salamina", "Supía", "Neira", "Palestina", "Aranzazu",
    "Filadelfia", "Marmato", "Belalcázar", "Risaralda", "San José", "Viterbo",
    "Pácora", "Manzanares", "Marquetalia", "Pensilvania", "Samaná", "Victoria",
    "La Merced", "Marulanda", "Norcasia",
  ],
  Caquetá: [
    "Florencia", "San Vicente del Caguán", "Puerto Rico", "El Doncello",
    "El Paujíl", "La Montañita", "Belén de los Andaquíes", "Albania", "Curillo",
    "Morelia", "Milán", "Solano", "Solita", "Valparaíso",
    "Cartagena del Chairá", "San José del Fragua",
  ],
  Casanare: [
    "Yopal", "Aguazul", "Villanueva", "Tauramena", "Paz de Ariporo",
    "Monterrey", "Maní", "Trinidad", "Nunchía", "Hato Corozal", "Pore",
    "Támara", "Sácama", "La Salina", "Chámeza", "Recetor", "Sabanalarga",
    "Orocué", "San Luis de Palenque",
  ],
  Cauca: [
    "Popayán", "Santander de Quilichao", "Puerto Tejada", "Patía (El Bordo)",
    "Guapi", "Miranda", "Corinto", "Piendamó", "Timbío", "Caloto", "Cajibío",
    "Morales", "Silvia", "Totoró", "Puracé", "Sotará", "Timbiquí",
    "López de Micay", "El Tambo", "Bolívar", "Mercaderes", "Balboa", "Argelia",
    "Sucre", "Almaguer", "La Vega", "San Sebastián", "Rosas", "La Sierra",
    "Inzá", "Páez (Belalcázar)", "Jambaló", "Toribío", "Caldono", "Padilla",
    "Villa Rica", "Buenos Aires", "Suárez", "Guachené", "Florencia",
    "El Bordo",
  ],
  Cesar: [
    "Valledupar", "Aguachica", "Agustín Codazzi", "Bosconia",
    "La Jagua de Ibirico", "El Copey", "Chiriguaná", "Curumaní", "San Alberto",
    "Pailitas", "La Paz", "San Diego", "Manaure Balcón del Cesar", "Becerril",
    "El Paso", "Astrea", "Chimichagua", "Tamalameque", "Pelaya", "La Gloria",
    "González", "Río de Oro", "San Martín", "Gamarra", "Pueblo Bello",
  ],
  Chocó: [
    "Quibdó", "Istmina", "Condoto", "Tadó", "Riosucio", "Bahía Solano",
    "Nuquí", "Acandí", "Unguía", "Bojayá", "Bagadó", "Lloró", "Atrato",
    "Medio Atrato", "Río Quito", "Cértegui", "Unión Panamericana", "Nóvita",
    "San José del Palmar", "Sipí", "Medio San Juan", "Litoral del San Juan",
    "El Cantón del San Pablo", "Bajo Baudó (Pizarro)", "Medio Baudó",
    "Alto Baudó (Pie de Pató)", "Carmen del Darién", "Juradó",
    "El Carmen de Atrato", "Belén de Bajirá",
  ],
  Córdoba: [
    "Montería", "Cereté", "Lorica", "Sahagún", "Montelíbano", "Planeta Rica",
    "Tierralta", "Ciénaga de Oro", "San Andrés de Sotavento", "Puerto Libertador",
    "Ayapel", "Chinú", "Pueblo Nuevo", "San Pelayo", "Cotorra", "Momil",
    "Purísima", "San Antero", "San Bernardo del Viento", "Moñitos",
    "Los Córdobas", "Puerto Escondido", "Canalete", "Valencia", "Tuchín",
    "San José de Uré", "La Apartada", "Buenavista", "Chimá",
  ],
  Cundinamarca: [
    "Soacha", "Fusagasugá", "Facatativá", "Zipaquirá", "Chía", "Girardot",
    "Mosquera", "Madrid", "Funza", "Cajicá", "Ubaté", "Cota", "Sibaté",
    "La Calera", "Tocancipá", "Villeta", "Tenjo", "Gachetá", "Anapoima",
    "Cogua", "Nemocón", "Tabio", "Sopó", "Gachancipá", "Sesquilé", "Suesca",
    "Chocontá", "Villapinzón", "Machetá", "Manta", "Tibirita", "Guatavita",
    "Guasca", "Junín", "Gama", "Ubalá", "Gachalá", "Medina", "Paratebueno",
    "Cáqueza", "Chipaque", "Une", "Fosca", "Quetame", "Guayabetal", "Fómeque",
    "Choachí", "Ubaque", "El Colegio", "Tena", "La Mesa", "Anolaima",
    "Cachipay", "Zipacón", "Bojacá", "El Rosal", "Subachoque", "San Francisco",
    "Supatá", "La Vega", "Nocaima", "Sasaima", "Nimaima", "Vergara", "Útica",
    "Quebradanegra", "Guaduas", "Puerto Salgar", "Caparrapí", "Yacopí",
    "La Palma", "Topaipí", "El Peñón", "Paime", "San Cayetano", "Villagómez",
    "Pacho", "San Juan de Rioseco", "Vianí", "Bituima", "Chaguaní", "Pulí",
    "Beltrán", "Guataquí", "Nariño", "Jerusalén", "Tocaima", "Agua de Dios",
    "Nilo", "Ricaurte", "Apulo", "Viotá", "Silvania", "Tibacuy", "Pandi",
    "San Bernardo", "Venecia", "Cabrera", "Pasca", "Arbeláez", "Granada",
    "Gutiérrez", "Simijaca", "Susa", "Fúquene", "Guachetá", "Lenguazaque",
    "Cucunubá", "Tausa", "Carmen de Carupa",
  ],
  Guainía: ["Inírida", "Barranco Minas", "Mapiripana", "San Felipe", "Puerto Colombia", "La Guadalupe", "Cacahual", "Pana Pana", "Morichal"],
  Guaviare: ["San José del Guaviare", "El Retorno", "Calamar", "Miraflores"],
  Huila: [
    "Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre", "Gigante",
    "Palermo", "Aipe", "San Agustín", "Rivera", "Timaná", "Suaza", "Guadalupe",
    "Tarqui", "Altamira", "El Pital", "Agrado", "El Agrado", "Paicol", "Tesalia",
    "Nátaga", "Yaguará", "Íquira", "Santa María", "Teruel", "Palestina",
    "Acevedo", "Isnos", "Saladoblanco", "Oporapa", "Elías", "Salado",
    "Villavieja", "Tello", "Baraya", "Colombia", "Hobo", "Algeciras",
    "La Argentina",
  ],
  "La Guajira": [
    "Riohacha", "Maicao", "Uribia", "Fonseca", "San Juan del Cesar",
    "Villanueva", "Barrancas", "Manaure", "Albania", "Dibulla", "Hatonuevo",
    "Distracción", "El Molino", "La Jagua del Pilar", "Urumita",
  ],
  Magdalena: [
    "Santa Marta", "Ciénaga", "Fundación", "El Banco", "Plato", "Zona Bananera",
    "Aracataca", "Pivijay", "Sitionuevo", "Puebloviejo", "Algarrobo",
    "Ariguaní (El Difícil)", "Chibolo", "El Retén", "Fonseca", "Guamal",
    "Nueva Granada", "Pedraza", "Pijiño del Carmen", "Remolino", "Salamina",
    "San Sebastián de Buenavista", "San Zenón", "Santa Ana", "Santa Bárbara de Pinto",
    "Tenerife", "Zapayán", "Cerro de San Antonio", "Concordia", "El Piñón",
    "Pijiño", "Sabanas de San Ángel",
  ],
  Meta: [
    "Villavicencio", "Acacías", "Granada", "Puerto López", "San Martín",
    "Cumaral", "Restrepo", "Puerto Gaitán", "Guamal", "Castilla la Nueva",
    "Cubarral", "El Dorado", "El Calvario", "San Juanito", "Fuente de Oro",
    "San Carlos de Guaroa", "Barranca de Upía", "Cabuyaro", "Puerto Lleras",
    "Puerto Rico", "Puerto Concordia", "Mapiripán", "Vistahermosa",
    "Uribe", "Mesetas", "Lejanías", "El Castillo", "San Juan de Arama",
    "La Macarena", "Cumaribo",
  ],
  Nariño: [
    "Pasto", "Ipiales", "Tumaco", "Túquerres", "La Unión", "Samaniego",
    "Sandoná", "Barbacoas", "Cumbal", "Pupiales", "Ricaurte", "El Charco",
    "La Cruz", "Buesaco", "Chachagüí", "Yacuanquer", "Tangua", "Consacá",
    "Ancuya", "Linares", "Providencia", "Sapuyes", "Guaitarilla", "Imués",
    "Ospina", "Iles", "Contadero", "Córdoba", "Potosí", "Gualmatán",
    "Aldana", "Guachucal", "Carlosama (Cuaspud)", "Puerres", "Funes",
    "Los Andes (Sotomayor)", "El Rosario", "Leiva", "Policarpa", "Cumbitara",
    "El Peñol", "Taminango", "San Lorenzo", "Arboleda", "Belén", "Colón (Génova)",
    "San Pablo", "San Bernardo", "Albán (San José)", "El Tablón de Gómez",
    "Chachagüí", "Mallama (Piedrancha)", "Santacruz (Guachavés)", "Magüí (Payán)",
    "Roberto Payán", "Olaya Herrera (Bocas de Satinga)", "Mosquera",
    "La Tola", "Santa Bárbara (Iscuandé)", "Francisco Pizarro (Salahonda)",
  ],
  "Norte de Santander": [
    "Cúcuta", "Ocaña", "Villa del Rosario", "Los Patios", "Pamplona", "Tibú",
    "El Zulia", "Chinácota", "Ábrego", "Sardinata", "Puerto Santander",
    "San Cayetano", "El Carmen", "Convención", "Teorama", "El Tarra",
    "Hacarí", "La Playa", "San Calixto", "La Esperanza", "Bochalema",
    "Durania", "Ragonvalia", "Herrán", "Toledo", "Labateca", "Chitagá",
    "Silos", "Cácota", "Mutiscua", "Pamplonita", "Cucutilla", "Arboledas",
    "Gramalote", "Lourdes", "Salazar", "Santiago", "Villa Caro", "Bucarasica",
    "El Tarra", "Cáchira", "La Esperanza", "Villacaro",
  ],
  Putumayo: [
    "Mocoa", "Puerto Asís", "Orito", "Valle del Guamuez (La Hormiga)",
    "Villagarzón", "Sibundoy", "Puerto Caicedo", "Puerto Guzmán",
    "Puerto Leguízamo", "San Miguel (La Dorada)", "Colón", "Santiago",
    "San Francisco",
  ],
  Quindío: [
    "Armenia", "Calarcá", "La Tebaida", "Montenegro", "Quimbaya", "Circasia",
    "Filandia", "Salento", "Génova", "Córdoba", "Buenavista", "Pijao",
  ],
  Risaralda: [
    "Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia", "Marsella",
    "Belén de Umbría", "Quinchía", "Apía", "Santuario", "Guática", "Balboa",
    "La Celia", "Pueblo Rico", "Mistrató", "Pereira",
  ],
  "San Andrés y Providencia": ["San Andrés", "Providencia y Santa Catalina"],
  Santander: [
    "Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja",
    "San Gil", "Barbosa", "Socorro", "Málaga", "Vélez", "Lebrija",
    "Sabana de Torres", "Rionegro", "Cimitarra", "Puerto Wilches", "Landázuri",
    "El Playón", "Matanza", "Suratá", "California", "Charta", "Tona",
    "Los Santos", "Zapatoca", "Betulia", "San Vicente de Chucurí", "El Carmen de Chucurí",
    "Simacota", "Chima", "Contratación", "Guacamayo", "Santa Helena del Opón",
    "Aguada", "Barichara", "Cabrera", "Villanueva", "Curití", "Pinchote",
    "Cepitá", "Jordán", "Aratoca", "Onzaga", "San Joaquín", "Mogotes",
    "San Andrés", "Molagavita", "Cerrito", "Concepción", "Enciso", "San Miguel",
    "Macaravita", "Capitanejo", "Carcasí", "Guaca", "Guadalupe", "Oiba",
    "Guapotá", "Palmar", "Palmas del Socorro", "Confines", "Gámbita",
    "Chipatá", "Guavatá", "Puente Nacional", "Jesús María", "La Belleza",
    "Sucre", "Bolívar", "El Peñón", "La Paz", "Aguada", "Florián",
    "Albania", "Puerto Parra", "Betulia", "Galán", "Hato", "Palmar",
    "Encino", "Coromoro", "Charalá", "Ocamonte", "Páramo", "Valle de San José",
  ],
  Sucre: [
    "Sincelejo", "Corozal", "Sampués", "San Marcos", "San Onofre", "Tolú",
    "Coveñas", "Majagual", "Sincé", "Los Palmitos", "Morroa", "Colosó",
    "Chalán", "Ovejas", "Toluviejo", "Palmito", "San Antonio de Palmito",
    "Betulia", "Buenavista", "Galeras", "El Roble", "San Juan de Betulia",
    "San Pedro", "San Benito Abad", "La Unión", "Caimito", "Sucre",
    "Guaranda", "Coveñas",
  ],
  Tolima: [
    "Ibagué", "Espinal", "Melgar", "Honda", "Líbano", "Chaparral", "Mariquita",
    "Flandes", "Purificación", "Guamo", "Fresno", "Cajamarca", "Lérida",
    "Venadillo", "Armero (Guayabal)", "Ambalema", "Piedras", "Alvarado",
    "San Luis", "Valle de San Juan", "Rovira", "Roncesvalles", "San Antonio",
    "Ortega", "Coyaima", "Natagaima", "Saldaña", "Coello", "Suárez",
    "Prado", "Dolores", "Alpujarra", "Villarrica", "Cunday", "Icononzo",
    "Carmen de Apicalá", "Falan", "Palocabildo", "Fresno", "Casabianca",
    "Herveo", "Villahermosa", "Murillo", "Santa Isabel", "Anzoátegui",
    "Rioblanco", "Planadas", "Ataco",
  ],
  "Valle del Cauca": [
    "Cali", "Buenaventura", "Palmira", "Tuluá", "Cartago", "Buga", "Jamundí",
    "Yumbo", "Florida", "Candelaria", "Zarzal", "Sevilla", "El Cerrito",
    "Roldanillo", "La Unión", "Pradera", "Guacarí", "Ginebra", "Andalucía",
    "Bugalagrande", "San Pedro", "Riofrío", "Trujillo", "Bolívar", "Toro",
    "La Victoria", "Obando", "Ansermanuevo", "El Águila", "El Cairo",
    "Argelia", "Versalles", "El Dovio", "Dagua", "La Cumbre", "Restrepo",
    "Vijes", "Yotoco", "Caicedonia", "Alcalá", "Ulloa", "Calima (El Darién)",
  ],
  Vaupés: ["Mitú", "Carurú", "Taraira", "Pacoa", "Papunahua", "Yavaraté"],
  Vichada: ["Puerto Carreño", "La Primavera", "Santa Rosalía", "Cumaribo"],
  "Bogotá D.C.": ["Bogotá D.C."],
};

/** Sentinel para cuando el municipio no está en la lista y se escribe a mano. */
export const OTHER_CITY = "__otra__";
